<a href="https://colab.research.google.com/github/JayTea704/mis433/blob/main/jb_assignment_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [1]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? jt
Welcome, jt!


In [7]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')
f = float(f)

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 45
45.0
45.0F is 7.222222222222222 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [14]:
# complete your program here
c = input('Please enter the temperature in Celcius: ')

print(c)
c = float(c)

#Fahrenheit = (Celcius * 9/5) + 32
f = (c * 9/5) + 32

print(f'{c}C is {f} in Fahrenheit. ')

Please enter the temperature in Celcius: 60
60
60.0C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [16]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? (c or f) ')

d = float(d)

if m == "c":
  f = (d * 9/5) + 32
  print(f'{d}C is {f} in Fahrenheit. ')

if m == "f":
  c = (d - 32) * 5/9
  print(f'{d}F is {c} in Celsius. ')



Please enter the temperature: 45
Is this in Celsius or Fahrenheit? (c or f) f
45.0F is 7.222222222222222 in Celsius. 


## Question 2

Have some fun with strings.

In [23]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [24]:
# Find the length of this sentence.
print(len(sentence))

48


In [25]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [26]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[11:-11])

ap. Show me the code - Lin


In [27]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split())

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [32]:
# Given the sentence, output a list of words in lowercase (without symbols such as '.' and '-').
print(sentence.lower().replace('.', '').replace('-', ' ').split())

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [35]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
total = 0
#vowels = 'aeiou'
for v in vowels:
  total += sentence.lower().count(v)

print(total)


13


In [36]:
# Find the positions (indexes) of all vowels in the sentence.
positions = []

for i in range(len(sentence)):
    if sentence[i].lower() in vowels:
        positions.append(i)

print(positions)

[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [37]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []

for n in range(5):
    cubes.append(n ** 3)

print(cubes)


[0, 1, 8, 27, 64]


In [38]:
# Use list comprehension to create the same list
cubes = [n ** 3 for n in range(5)]

print(cubes)

[0, 1, 8, 27, 64]


In [39]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"

vowels = 'aeiou'

positions = [i for i in range(len(sentence)) if sentence[i].lower() in vowels]

print(positions)

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [40]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')

# add your code here
n = int(n)
a, b = 0, 1
for i in range(n):
    fibonacci.append(a)
    a, b = b, a + b

print(fibonacci)

How many numbers do you want? 8
[0, 1, 1, 2, 3, 5, 8, 13]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [41]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66
}

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66}


In [43]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Moderna
0.95


In [46]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [47]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914, 'Sinovac': 0.5038}


In [44]:
# Print vaccines with efficacy lower than 90%.
for vaccine, efficacy in v_dict.items():
    if efficacy < 0.90:
        print(vaccine)

AstraZeneca
Johnson & Johnson


In [48]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']

print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.914}


In [49]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for ch in sentence:
    if ch != ' ':
        if ch in ch_dict:
            ch_dict[ch] += 1
        else:
            ch_dict[ch] = 1
# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [50]:
import numpy as np

In [53]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
evens = np.array([2 * n for n in range(1, 21)])
print(evens)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [54]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
odds = np.array([2 * n - 1 for n in range(1, 21)])
print(odds)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [55]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
arr = np.arange(100).reshape(10, 10)

print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [56]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
M.shape

(10, 10)

In [57]:
# Count the numbers in M with an absolute value greater than 1.
count = np.sum(np.abs(M) > 1)

print(count)

24


In [64]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')
r = int(r)
# Input the number of rows (input another integer >= 3)
c = input('column count: ')
c = int(c)
# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size = (r,c))
arr

Row count: 4
column count: 6


array([[10, 17, 13, 19, 17, 13],
       [14, 19, 11, 16, 16, 12],
       [16, 15, 16, 17, 18, 14],
       [16, 10, 13, 18, 18, 18]])

In [65]:
# output the element in the first row and the third column
arr[0, 2]

np.int64(13)

In [66]:
# output the element in the second row and the last column
arr[1, -1]

np.int64(12)

In [68]:
# output the second row of the array
arr[1,:]

array([14, 19, 11, 16, 16, 12])

In [70]:
# output the second last row of the array
arr[-2,:]

array([16, 15, 16, 17, 18, 14])

In [71]:
# output the second column of the array
arr[:,1]

array([17, 19, 15, 10])

In [72]:
# output the second last column of the array
arr[:,-2]

array([17, 16, 18, 18])

In [73]:
# output the upper-left 3x3 sub-array
arr[:3, :3]

array([[10, 17, 13],
       [14, 19, 11],
       [16, 15, 16]])

In [75]:
# output the bottom-left 3x3 sub-array
arr[-3:, :3]

array([[14, 19, 11],
       [16, 15, 16],
       [16, 10, 13]])

In [76]:
# output the upper-right 3x3 sub-array
arr[:3, -3:]

array([[19, 17, 13],
       [16, 16, 12],
       [17, 18, 14]])

In [77]:
# output the bottom-right 3x3 sub-array
arr[-3:, -3:]

array([[16, 16, 12],
       [17, 18, 14],
       [18, 18, 18]])

In [79]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
# Reshape A to a 5x10 array in the following format:
A = A.reshape(5, 10)
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [80]:
# add a row [51,...,60] to A
new_row = np.arange(51, 61)

A = np.vstack([A, new_row])

print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [81]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.vsplit(A, 2)

print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [82]:
# Add 10 to each element of A
A = A + 10

print(A)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [83]:
# Calculate the square root of each element in A
np.sqrt(A)

array([[3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669],
       [7.81024968, 7.87400787, 7.93725393, 8.        , 8.06225775,
        8.1240384 , 8.18535277, 8.24621125, 8.30662386, 8.36660027]])

In [84]:
# Above, we should have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [85]:
# Print the mean, standard devietion of all numbers in M
print('Mean:', np.mean(M))
print('Standard deviation:', np.std(M))

Mean: 0.05997132294048566
Standard deviation: 0.8737364457874387


In [86]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print('Maximum:', np.max(M))
print('3rd quartile:', np.percentile(M, 75))
print('Median:', np.median(M))
print('1st quartile:', np.percentile(M, 25))
print('Minimum:', np.min(M))

Maximum: 2.3184456468875103
3rd quartile: 0.6876978363803204
Median: 0.043883412007520314
1st quartile: -0.4705970207912409
Minimum: -2.4291713333612606
